// src/data/aiContentData.ts

export interface Section {
  id: string;
  title: string;
  highlight?: string;
  description?: string[];
  list?: string[];
}

export const aiContentSections: Section[] = [
  {
    id: "intro",
    title: "AI Content",
    highlight: "Detector",
    description: [
      "Our AI Content Detector makes it easy to identify whether text is written by a human, generated by AI, or refined with the help of AI tools.",
      "With AI-generated text becoming more common, this tool ensures transparency and trust in digital content. Simply paste your text or upload a document, and in seconds you’ll get a clear analysis showing how much of it is AI vs. human-written."
    ]
  },
  {
    id: "why",
    title: "Why Use Our AI Content",
    highlight: "Detector",
    description: [
      "Manually spotting AI-written text is extremely difficult. Even professional editors may struggle to tell the difference, since AI models are designed to mimic human writing styles.",
      "Our AI Content Detector uses advanced algorithms to analyze sentence structure, word choice, and writing patterns. With it, you can:"
    ],
    list: [
      "Identify text generated entirely or partly by AI.",
      "Verify blended (co-written) documents, essays, or online content.",
      "Detect intentionally manipulated passages.",
      "Save time by reducing manual guesswork."
    ]
  },
  {
    id: "info",
    title: "What Information Does the AI",
    highlight: "Detector",
    description: [
      "When you analyze text with our tool, you’ll get a detailed percentage breakdown, showing the likelihood that the text is:"
    ],
    list: [
      "AI-generated – Entirely written by an AI model.",
      "AI-generated & Edited – AI text that has been lightly revised or edited by humans.",
      "Human-written & Refined – Mostly human-written but improved with AI assistance.",
      "Human-written – Authored completely by a human without AI involvement."
    ]
  },
  {
    id: "understanding",
    title: "Understanding",
    highlight: "AI-Generated Content",
    description: [
      "AI writing tools are trained on massive datasets and can produce human-like text. While these tools are useful for drafting, summarizing, or idea generation, they also raise concerns about:"
    ],
    list: [
      "Academic Integrity – Students using AI to write assignments.",
      "Publishing Standards – Ensuring original and authentic content.",
      "Business Communication – Writing that appears too generic or less human-focused."
    ]
  }
];
